""" Updated projects

Revision ID: 17eef06ce807
Revises: f3b8aad46318
Create Date: 2025-06-22 14:38:38.570593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17eef06ce807'
down_revision = 'f3b8aad46318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('link')

    op.create_table('file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='file_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_pkey')
    )
    # ### end Alembic commands ###
